### ISSUE TITLE
Validate returns http code 400 on invalid address?

### ISSUE THREAD

**Issue by Jud** [peterruggero/postmaster-php#13]
Just messing around with the address validation examples, I notice that if I change "701 Brazos St. Suite 1616" to "7901 Brazos St. Suite 1616", the address validation endpoint returns a 400 error instead of an array of suggestions.

After looking at the tests, I see this is expected behavior, but at what point is an address so invalid that it returns a 400 instead of suggestions? Does this just happen when there are no suggestions?

When trying to validate user supplied addresses, is the expected implementation to wrap all validation calls in try/catch (since the php library throws on 400 errors)?

**Comment by drosenthal** [comment]
Hey Jud,

Sorry for the delay here. We're looking into this now.

**Comment by drosenthal** [comment]
So the algorithm we use will return a 400 error if there are no suggestions. This generally indicates a very bad address or one that doesn't exist. It really depends on the address that you input.

As for wrapping your calls, we recommend it as a best practice to handle the 400 error.

Again, sorry for the delay!
