### ISSUE TITLE
Correct way to capture API errors

### ISSUE THREAD

**Issue by maxapps** [peterruggero/postmaster-php#17]
While testing the PHP API for a new project, I received the following error, "Fatal error: Uncaught exception 'InvalidData_Error' with message 'APIError 111035: The maximum per package weight for the selected service from the selected country is 150.00 pounds.'".

Can you please provide information on how this type of error should be handled? At the moment it's generating a very ugly message in the middle of the normal HTML. I can easily trap the error but it would be preferable for it to be part of a "standard" response.

**Comment by CountZachula** [comment]
Hey @maxapps,

Thanks for trying out the Postmaster PHP library.

I apologize for the delay. Error responses are serialized into **Postmaster_Error** objects, which inherit from **Exception**. Please see Error.php in the source for more information. I've attached a snippet below of how something might be handled:

```
try {
    $result = Postmaster_AddressValidation::validate(array());
}
catch (Postmaster_Error $expected) {
    $json_body = $expected->getJsonBody();
    $http_body = $expected->getHttpBody();

    var_dump($json_body['message']);
}

----------------------------------------------------

CountZachula:postmaster-php $ php Example.php 
string(73) "Validation API error: city: Required, line1: Required, zip_code: Required"
```

Let me know if this helps. Thanks,
Z

**Comment by CountZachula** [comment]
Hey @maxapps,

Did this help any?

Thanks,
Z
