### ISSUE TITLE
Slight correction to the docs for Postmaster_TransitTimes::get()

### ISSUE THREAD

**Issue by maxapps** [peterruggero/postmaster-php#18]
The documentation for the Get Time function (i.e. Postmaster_TransitTimes::get()) response is slightly incorrect.

It states that the response includes a property named **services** which is an array of objects with **delivery_timestamp** and **service** properties. This may be true for the "raw" data but the PHP library returns just the array of objects (no services property).

Not a big deal but it would save people time if it were better documented somewhere.

**Comment by CountZachula** [comment]
Hey @maxapps,

Thanks for pointing this out. 

I believe the PHP library may actually reflect an older version of the documentation. After all, it is a living document that updates with the Postmaster API. I apologize if it's caused you any inconvenience. If it becomes a major issue and enough complaints come in, I'll make the change. For now, I'm hesitant on breaking the library for current users.

Check out the .NET and node.js libraries. They're a bit more up to date and are well aligned with the documentation. I maintain those 100% :).

Have a good one!
Z
